title: Site

sections:
  pages:
    type: pages
  info:
    type: fields
    fields:
      tags:
        label: Tags
        type: structure
        width: 1/2
        fields:
          tagname:
            type: text




